### ISSUE TITLE
Question about the CRFs

### ISSUE THREAD

**Issue by speedcell4** [LorrinWWW/Pyramid#1]
Hi~ Thanks for sharing the source code.
I noticed there are some CRF variants under `layers/crfs.py`, e.g., `CRF`, `DTCRF`, `DCCRF`, and `PyramidCRF`.
Could you please explain the differences between them? 
And seems you did not use any of them in the final model (I hope I correctly understood your paper), is that because the final evaluation results are not better than plain `softmax`?

**Comment by LorrinWWW** [comment]
Hi, yes, you understand correctly. We have tried using separate CRF layers for each decoding layer, but it does not show a significant difference than plain softmax, so it is not used in the final version. DTCRF and DCCRF are copied from other code bases designed for few-shot sequence labeling and have nothing to do with this work, so just ignore them. PyramidCRF is an experimental idea, the purpose is to design a special CRF to adapt to our model output. However, since it did not work as expected, it has been abandoned in the early iterations.

One possible explanation here is that in Pyramid, most tags are B-tags (except for the last layer), so the relationship between B-tag and I-tag does not need to be considered like sequence labeling. So CRF has little effect here. ~~We will remove them from the code to prevent misunderstandings.~~ We removed the CRF option, but we keep crf.py as a reference for anyone planning to use CRF to improve the model.

**Comment by speedcell4** [comment]
Thank you for your quick and detailed response. 
Could you please show me the repository that `DTCRF` and `DCCRF` were copied from? Just a little bit curious about the original motivation of such design.

**Comment by LorrinWWW** [comment]
That code is from one of our projects. DTCRF = "Dependency Transfer CRF", it is an implementation of [this paper](https://arxiv.org/abs/1906.08711) (not our work). Their core idea is to let different entity classes share the same transition matrix -- the transition scores between B-tag I-tag and O. Therefore, CRF layer can be applied in new entity types that are never seen before. DCCRF is our modified version, its performance is somewhat between CRF and DTCRF, but please note it is still a very preliminary idea and may have serious flaws so please be careful when reading and using it.

**Comment by speedcell4** [comment]
Thx~ 
Your replies are very helpful~
