### ISSUE TITLE
Tokenizers

### ISSUE THREAD

**Issue by DimasDMM** [LorrinWWW/Pyramid#4]
Hello Jue,

It seems that the script to generate the unified dataset is missing, so I am a bit confused about it. Basically, I am not sure how to tokenize each text: BERT uses `WordPieceTokenizer`, but this is different from the tokens of GloVe.

Since I have 3 different inputs (word embeddings, char embeddings and BERT), should I use 3 different tokenizers?

**Comment by LorrinWWW** [comment]
Let's illustrate by an example. Given input text "hello dimas", we build inputs as follows:
- The inputs for word embeddings are ['hello', 'dimas'], whose outputs are denoted [x^{w}('hello'), x^{w}('dimas')];
- The inputs for char embeddigns are [['h','e','l','l','o'], ['d','i','m','a','s']], whose outputs are denoted [x^{c}(['h','e','l','l','o']), x^{c}(['d','i','m','a','s'])], where x^{c}(*) picks the last hidden state of char-lstm as the aggregate representation of a sequence of characters (i.e., a word);
- The inputs for lm embeddings (BERT here) are ['hello', 'dim', '##as'], whose outputs are denoted [x^{'l}('hello'), x^{'l}('dim'), x^{'l}('##as')]. We average the word pieces within the same word (e.g., 'dim' and '##as' for 'dimas'), so the final embeddings are [x^{l}('hello'), x^{l}('dimas')] == [x^{'l}('hello'), (x^{'l}('dim') + x^{'l}('##as')) / 2]. 

If you are still not very clear, we refer you to [Flair](https://github.com/flairNLP/flair) to see how they generate embeddings from different sources (they support GloVe, Char, ELMo, Flair, BERT, etc.). But we need to note that our approach may not be optimal since it does not allow fine-tuning BERT. Maybe simply adopting the BERT tokenization and fine-tuning BERT will get better results for some datasets.

**Comment by DimasDMM** [comment]
Thanks a lot. Now it is very clear to me :)
